name: 'Check for Changes'

inputs:
  service:
    required: true
    type: string

outputs:
  changes:
    description: 'Whether there are changes in the service'

runs:
  using: 'composite'
  steps:
    - run: |
        if git diff --name-only HEAD^ HEAD | grep -q "^${{ inputs.service }}/"; then
          echo "changes=true" >> $GITHUB_ENV
          echo "::set-output name=changes::true"
        else
          echo "changes=false" >> $GITHUB_ENV
          echo "::set-output name=changes::false"
