apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-deployment
  labels:
    app: movies
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
      - name: moviesserver
        image: fouadallaoui/movies-microservice:latest
        ports:
        - containerPort: 3004

---
apiVersion: v1
kind: Service
metadata:
  name: movies-service

spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3004
  selector:
    app: movies



#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: movies-service
#
#spec:
#  selector:
#    app: movies
#  type: LoadBalancer
#  ports:
#    - protocol: TCP
#      port: 80  # The port exposed by the service
#      targetPort: 3001  # The port on which the container is listening

